In [15]:
import numpy as np

a = np.array([[1, 2, 3]]).reshape(3, 1)
b = np.array([[1, 2, 3]]).reshape(3, 1)

print(np.dot(a, b.T))

[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [13]:
a.reshape(3, 1)

array([[1],
       [2],
       [3]])

In [10]:
k = 4
z_t = np.random.randn(k, 1)  # Generating a random vector with standard normal distribution

# Calculate the outer product
outer_product = np.dot(z_t, z_t.T)
outer_product

array([[ 0.41136455,  1.87334492, -0.60365996,  0.41197526],
       [ 1.87334492,  8.5311706 , -2.74905387,  1.87612606],
       [-0.60365996, -2.74905387,  0.88584527, -0.60455614],
       [ 0.41197526,  1.87612606, -0.60455614,  0.41258687]])

In [11]:
print(z_t)

[[ 0.64137707]
 [ 2.92081677]
 [-0.94119354]
 [ 0.64232925]]
